apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: defult
  namespace: metallb-system
spec:
  addresses:
  - 192.168.4.0/24  #改成你可以路由的
  avoidBuggyIPs: true
